import { FDoptions } from "field-descriptions/lib";

export const states: string[] = [
  "California",
  "Texas",
  "Florida",
  "New York",
  "Illinois",
  "Ohio",
  "Georgia",
  "Pennsylvania",
  "Tennessee",
  "North Carolina",
  "Arizona",
  "Michigan",
  "Indiana",
  "New Jersey",
  "Wisconsin",
  "Missouri",
  "Minnesota",
  "Massachusetts",
  "Alabama",
  "Virginia",
  "Colorado",
  "Louisiana",
  "South Carolina",
  "Oklahoma",
  "Iowa",
  "Maryland",
  "Utah",
  "Kentucky",
  "Washington",
  "Arkansas",
  "Kansas",
  "Nevada",
  "Mississippi",
  "Connecticut",
  "Nebraska",
  "New Mexico",
  "Idaho",
  "Oregon",
  "South Dakota",
  "North Dakota",
  "West Virginia",
  "Rhode Island",
  "Montana",
  "Delaware",
  "Alaska",
  "New Hampshire",
  "Wyoming",
  "District Of Columbia",
  "Maine",
  "Hawaii",
  "Vermont",
  "Puerto Rico",
  "Guam",
  "United States Virgin Islands",
  "Northern Mariana Islands",
  "American Samoa",
  "US Military",
  "Veteran Affairs",
  "Federal Prisons",
  "Navajo Nation",
  "Grand Princess Ship",
  "Wuhan Repatriated",
  "Diamond Princess Ship",
];
export const FDefaults: FDoptions = {
  separator: ":",
  nameEdits: { bold: true },
};
